name: simclr_mimic
ckpt_dir: ckpt

dataset:
  proto: ImageDataset
  root: data/SELFSUP/mimic-cxr/
  file: image.tok
  image_path: data/images/
  load_memory: False
  ext: .jpg


model:
  proto: VQModel

trainor:
  optimizer: RAdam
  optim_params:
    lr: 0.001
  batch_size: 16
  lr_decay: ReduceLROnPlateau
  lr_decay_params:
    factor: 0.8
    patience: 5
    min_lr: 0.000001
    threshold: 0.01
    threshold_mode: abs
  epochs: 999
  early_stop: 20
  eval_start: 0
  early_stop_metric: validation_loss

validator:
  batch_size: 16
  splits: [ validate ]
